# Generated by Django 5.0.4 on 2024-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_orderplaced_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('RP', 'Rice & pasta'), ('MP', 'Meat & Poultry'), ('CDS', 'Chips, Dips & Snacks'), ('PC', 'Personal Care'), ('FV', 'Fruits & vegetables'), ('D', 'Dairy'), ('BP', 'Bakery & Pastry'), ('LD', 'Laundry & Detergents')], max_length=3),
        ),
    ]
